$(document).ready(function(){
    $('.iframe').mouseenter(function(){
        $('#transfer').fadeTo('slow',0);  
    })
    $('.iframe').mouseleave(function(){
        $('#transfer').fadeTo('slowa',1); 
        }) 
     $('.iframe').mouseenter(function(){
        $('#exchange').fadeTo('slow',0);  
    })
    $('.iframe').mouseleave(function(){
        $('#exchange').fadeTo('slow',1); 
        }) 
})